apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: calico-ee-global-netpol-headroom-ext-prod-canary-73
    app.upwork.com/runtime: eks
  name: default.allow-from-fluentd-73
spec:
  egress:
    - action: Allow
      destination:
        selector: all()
      source:
        selector: app.kubernetes.io/name == 'fluentd'
  order: 5
  selector: app.kubernetes.io/name == 'fluentd'
  types:
    - Egress
