apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: calico-ee-global-netpol-headroom-ext-prod-canary-93
    app.upwork.com/runtime: eks
  name: allow-from-vault-93
spec:
  egress:
    - action: Allow
      destination:
        selector: all()
      source:
        selector: app.kubernetes.io/name == 'vault'
  order: 5
  selector: app.kubernetes.io/name == 'vault'
  types:
    - Egress
