apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: upwork-gnp-100
spec:
  project: default
  source:
    repoURL: 'git@github.com:VerodaClient/argocd-charts.git'
    targetRevision: HEAD
    helm:
      values: |
        globalDefaultDenyNetworkPolicies:
          enabled: true
        namespaceNetworkPolicies:
          enabled: true
          deny:
            - calico-system
            - kube-system
        hostNetworkPolicies:
          enabled: true
        podNetworkPolicies:
          enabled: true
        kubectlExecAccess:
          enabled: true
        failSafeNetworkPolicies:
          enabled: false
        portsEgress:
          tcp:
            - 443   # pull docker images images
          udp:
            - 123 # NTP
        portsNodeIngress:
          tcp:
            - 50051 # aws-node to aws-node
          udp:
            - 123 # NTP
        portsIngress:
          tcp:
            - 10250 # kubelet
          udp:
            - 53  # DNS
        calicoEnterprise:
          enabled: true
    chart: charts/global-network-policies
  destination:
    server: 'https://40B4FF60AF91508CE89E88DE3DECE44B.gr7.ca-central-1.eks.amazonaws.com'
    namespace: calico-system
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
