apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calico-cloud-crds
  namespace: argocd
  annotations:
      argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    #repoURL: 'https://installer.calicocloud.io/charts'
    path: charts/calico-cloud-crds
    repoURL: 'git@github.com:VerodaClient/argocd-charts.git'
    targetRevision: "v1.16.2"
    helm:
      valueFiles:
      - values.yaml
  destination:
    name: ce-mgmt
    namespace: calico-cloud
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
#  metadata:
#    annotations:
#      argocd.argoproj.io/sync-wave: "1"

