apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: leons-calico-cloud
  namespace: argocd
  annotations:
      argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: 'git@github.com:VerodaClient/argocd-charts.git'
    path: charts/calico-cloud
    targetRevision: HEAD
    helm:
      releaseName: "calico-cloud"
      valueFiles:
      - values.yaml
      values: |
        nameOverride: "calico-cloud"
        fullnameOverride: "calico-cloud"
  destination:
    name: ce-mgmt
    namespace: calico-cloud
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

