---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: tigera-pull-secret
  namespace: tigera-operator
spec:
  encryptedData:
    .dockerconfigjson: AgAaQIioQH/qx6rkWibqhSS1Xki2xwSQ/UtjqPeG87SkhfPAZbvAx0jdYQfW09c+dYqqRerOb93i85dKZFjQJ6BMlDR1+95f/irCW26G1Qh1xk4WzMRbXTjVWn2cpH0gm+nGq2fQVP9spDRiOpQz1YW7yD4FBzqnBBMS4UzJDyX6tmaIhIqmB0nazIUwsFSBKAH64hIy+wQ6SZayfwNACmp18zrwp2OuGCEytD+rOqp2+jVsctisFdweuyhTABct+v6mGTWST+b84Kyc5JvDa1HVQaS6KiieRruS1m6CXu4tBDbOXSKNQi293GwZhvQA/5Bu2sfX/FSx7XhEwcQyxcCe4MMhKIy25PVk/+ICaesN4uGvUuIaDlFQFJMLPvRCVhZySj9TS7VEwthUx002nh4Ti44e/icUBEHQ49N/lVqYY3FUIOIzmNnjDwVItZXtsUwhK3FHD2at7TntGSf0FSvOM/Fzr46hgxW7KswcitzZA1pCbMbwG27ao6lAmdVEFMrlkwXI6lJ/Q4pp3IfTFPEiHKYBA5vIdvo4hHprpqhDMUdWylEvHmk8XU64CnEDAA0EIAqZK7w6tEb+7VivDeJkJrwNwa9qHW5aZZEHcRRdnkUYmOo4TkSwSa76TkNpe9Rno4W3jmHXyPmWwI6YsJSFR/OcKqJSOqQ+CoHxHwFjRoSqG4nE7KRlSw70Ivhp/TcB0xCdWdVTI7B+O4Fv5+ZDSqIpBAuQqr5XPUGvHMvPP3Hpa3vkdZVbUixoP7o3YMIl3liL9TEcOFlZEn6vRt0+EOzWNA+WDaYUmmiD1xoig1gpmaYD7jIiSFBcn66qHMC0vxjndL1/BNPOCze/L++Zk+KZt9ERSmEVwPVQkhn/9gsfGbeOApt+B45O9GVXpZ5OpvirhYAwKQJEW4KV3WvinRJqFaBZVCZT+RPRN2GVlTuYt0z3AA+EpMcuCnef9G/wKeNH+RgjjqQYAwE=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: tigera-pull-secret
      namespace: tigera-operator
    type: kubernetes.io/dockerconfigjson
