{{ if or (and .Values.mgmtclustercert (eq .Values.mgmtclustercert.enabled true)) (and .Values.standalonecluster (eq .Values.standalonecluster.enabled true))}}

---
apiVersion: projectcalico.org/v3
kind: LicenseKey
metadata:
  creationTimestamp: null
  name: default
spec:
  certificate: |+
    -----BEGIN CERTIFICATE-----
    MIIFxjCCA66gAwIBAgIQVq3rz5D4nQF1fIgMEh71DzANBgkqhkiG9w0BAQsFADCB
    tTELMAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNh
    biBGcmFuY2lzY28xFDASBgNVBAoTC1RpZ2VyYSwgSW5jMSIwIAYDVQQLDBlTZWN1
    cml0eSA8c2lydEB0aWdlcmEuaW8+MT8wPQYDVQQDEzZUaWdlcmEgRW50aXRsZW1l
    bnRzIEludGVybWVkaWF0ZSBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkwHhcNMTgwNDA1
    MjEzMDI5WhcNMjAxMDA2MjEzMDI5WjCBnjELMAkGA1UEBhMCVVMxEzARBgNVBAgT
    CkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBGcmFuY2lzY28xFDASBgNVBAoTC1Rp
    Z2VyYSwgSW5jMSIwIAYDVQQLDBlTZWN1cml0eSA8c2lydEB0aWdlcmEuaW8+MSgw
    JgYDVQQDEx9UaWdlcmEgRW50aXRsZW1lbnRzIENlcnRpZmljYXRlMIIBojANBgkq
    hkiG9w0BAQEFAAOCAY8AMIIBigKCAYEAwg3LkeHTwMi651af/HEXi1tpM4K0LVqb
    5oUxX5b5jjgi+LHMPzMI6oU+NoGPHNqirhAQqK/k7W7r0oaMe1APWzaCAZpHiMxE
    MlsAXmLVUrKg/g+hgrqeije3JDQutnN9h5oZnsg1IneBArnE/AKIHH8XE79yMG49
    LaKpPGhpF8NoG2yoWFp2ekihSohvqKxa3m6pxoBVdwNxN0AfWxb60p2SF0lOi6B3
    hgK6+ILy08ZqXefiUs+GC1Af4qI1jRhPkjv3qv+H1aQVrq6BqKFXwWIlXCXF57CR
    hvUaTOG3fGtlVyiPE4+wi7QDo0cU/+Gx4mNzvmc6lRjz1c5yKxdYvgwXajSBx2pw
    kTP0iJxI64zv7u3BZEEII6ak9mgUU1CeGZ1KR2Xu80JiWHAYNOiUKCBYHNKDCUYl
    RBErYcAWz2mBpkKyP6hbH16GjXHTTdq5xENmRDHabpHw5o+21LkWBY25EaxjwcZa
    Y3qMIOllTZ2iRrXu7fSP6iDjtFCcE2bFAgMBAAGjZzBlMA4GA1UdDwEB/wQEAwIF
    oDATBgNVHSUEDDAKBggrBgEFBQcDAjAdBgNVHQ4EFgQUIY7LzqNTzgyTBE5efHb5
    kZ71BUEwHwYDVR0jBBgwFoAUxZA5kifzo4NniQfGKb+4wruTIFowDQYJKoZIhvcN
    AQELBQADggIBAAK207LaqMrnphF6CFQnkMLbskSpDZsKfqqNB52poRvUrNVUOB1w
    3dSEaBUjhFgUU6yzF+xnuH84XVbjD7qlM3YbdiKvJS9jrm71saCKMNc+b9HSeQAU
    DGY7GPb7Y/LG0GKYawYJcPpvRCNnDLsSVn5N4J1foWAWnxuQ6k57ymWwcddibYHD
    OPakOvO4beAnvax3+K5dqF0bh2Np79YolKdIgUVzf4KSBRN4ZE3AOKlBfiKUvWy6
    nRGvu8O/8VaI0vGaOdXvWA5b61H0o5cm50A88tTm2LHxTXynE3AYriHxsWBbRpoM
    oFnmDaQtGY67S6xGfQbwxrwCFd1l7rGsyBQ17cuusOvMNZEEWraLY/738yWKw3qX
    U7KBxdPWPIPd6iDzVjcZrS8AehUEfNQ5yd26gDgW+rZYJoAFYv0vydMEyoI53xXs
    cpY84qV37ZC8wYicugidg9cFtD+1E0nVgOLXPkHnmc7lIDHFiWQKfOieH+KoVCbb
    zdFu3rhW31ygphRmgszkHwApllCTBBMOqMaBpS8eHCnetOITvyB4Kiu1/nKvVxhY
    exit11KQv8F3kTIUQRm0qw00TSBjuQHKoG83yfimlQ8OazciT+aLpVaY8SOrrNnL
    IJ8dHgTpF9WWHxx04DDzqrT7Xq99F9RzDzM7dSizGxIxonoWcBjiF6n5
    -----END CERTIFICATE-----
  token: eyJhbGciOiJBMTI4R0NNS1ciLCJjdHkiOiJKV1QiLCJlbmMiOiJBMTI4R0NNIiwiaXYiOiJoQndHc0FVazVESWEySVdTIiwidGFnIjoiVF9wWFVObXVlUXpOdFRNSHB3d04wQSIsInR5cCI6IkpXVCJ9.DVDVHQCc9uf59sFDNg-mcw.B3X3QUTLz46zuI_C.BvPqpkqRW3AiiTGJa5-fVBlmwXDYAQF_hRTgUThfEgwVf5imi2FS02lIY6E3qMxhsqDWi30KdKElgdAK1wSIhfm8YXmODjkL2KS0Gb6iyT6CbnLlpiOkhKogOb1Ty4o7VSaqNuL8ZArwxsmNE5tpoyAO8ypwOJCoYj4cfU29_hZunpB35EcG_TXhw6sCECSzN-RJnLrpOZ6L6TTKOnpmClnOdvkB1v6-5ytgVbXcU-uP0gGfGN7OdoCet2ygTI6RxEuegh8pCM_iQCRBXGYBjTg6emJN54_Q-KLJxIRfm1-ZEO24J-mAdTE2vBKCmNiL8uph4J6kHGXUxmiqdlc0XMVl00IaFLHuJSy4bjKylOV9Q486EK9225p2kizFV-eR46UMcowJoYin3ZwWSgu99ZvFK_PURbzPmjR7--eUjkKWaoHHKt7CDn_VsktLeD9qfy38uHWcq0Rz1kO6JRFU6cVquA666CGmFg3ObnWHklFn8dR5vFLBgipLcMIhVTAwyOPDJF6wg9d1tq6rg86_haIyiqk2yo4hwkyMziNkgIomt6g5omYUaFWUfDbKqwYkLIZsxTl8DDWYnZmNHASy8hhgbtdj4tl1VYn4MuqKMuAJzrIsvxkxD_Kd74pwwCc5LK10UiIgPM9fLR5p9zmeI9AErJdzX7QYWu6QDWMz7JpObrrnvlgbrM8SytM01GBNPMQifw7vQDRnzwnmM4zsGloJCAw3xmKBgdkQcBtjr61_bGPavhMOVT1ioZp93WY-657WFN1afsq1nva0X-RF70CblWzPsXvZMmoi5WOCfkx1_0eqLnSgFgH-LD5wcdo6iTvDQii-Qm8jXfOCyTah47KcRnyPGAdEN1lSsTab-7leB8xBijZPU0qxfLfwwZqGukEBcbzqEqNp8zySjJbKJ9Wm0W_E4zsUmHL4W3hbnGcQkktr-5quikv6kta1ac6XRGzPaFNtWlR8bzyC2ZfowbSFpsoJV6IjXYu-g7PVNew-D3uHv_ww-VYOdp8UadSLcBgKapbzHr5ygkvhBVej3EAyTNzfZHiZBC1auzWXLqrohpSqy4vFspTAZR-0EbyXv4h1p4NRMgUq901PxazqSyzO.9HFAtHTQ-CZSF_sAdUcZlg

{{ end }}
