{{ if or (and .Values.mgmtclustercert (eq .Values.mgmtclustercert.enabled true)) (and .Values.standalonecluster (eq .Values.standalonecluster.enabled true))}}

apiVersion: projectcalico.org/v3
kind: LicenseKey
metadata:
  creationTimestamp: null
  name: default
spec:
  certificate: |+
    -----BEGIN CERTIFICATE-----
    MIIFxjCCA66gAwIBAgIQVq3rz5D4nQF1fIgMEh71DzANBgkqhkiG9w0BAQsFADCB
    tTELMAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNh
    biBGcmFuY2lzY28xFDASBgNVBAoTC1RpZ2VyYSwgSW5jMSIwIAYDVQQLDBlTZWN1
    cml0eSA8c2lydEB0aWdlcmEuaW8+MT8wPQYDVQQDEzZUaWdlcmEgRW50aXRsZW1l
    bnRzIEludGVybWVkaWF0ZSBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkwHhcNMTgwNDA1
    MjEzMDI5WhcNMjAxMDA2MjEzMDI5WjCBnjELMAkGA1UEBhMCVVMxEzARBgNVBAgT
    CkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBGcmFuY2lzY28xFDASBgNVBAoTC1Rp
    Z2VyYSwgSW5jMSIwIAYDVQQLDBlTZWN1cml0eSA8c2lydEB0aWdlcmEuaW8+MSgw
    JgYDVQQDEx9UaWdlcmEgRW50aXRsZW1lbnRzIENlcnRpZmljYXRlMIIBojANBgkq
    hkiG9w0BAQEFAAOCAY8AMIIBigKCAYEAwg3LkeHTwMi651af/HEXi1tpM4K0LVqb
    5oUxX5b5jjgi+LHMPzMI6oU+NoGPHNqirhAQqK/k7W7r0oaMe1APWzaCAZpHiMxE
    MlsAXmLVUrKg/g+hgrqeije3JDQutnN9h5oZnsg1IneBArnE/AKIHH8XE79yMG49
    LaKpPGhpF8NoG2yoWFp2ekihSohvqKxa3m6pxoBVdwNxN0AfWxb60p2SF0lOi6B3
    hgK6+ILy08ZqXefiUs+GC1Af4qI1jRhPkjv3qv+H1aQVrq6BqKFXwWIlXCXF57CR
    hvUaTOG3fGtlVyiPE4+wi7QDo0cU/+Gx4mNzvmc6lRjz1c5yKxdYvgwXajSBx2pw
    kTP0iJxI64zv7u3BZEEII6ak9mgUU1CeGZ1KR2Xu80JiWHAYNOiUKCBYHNKDCUYl
    RBErYcAWz2mBpkKyP6hbH16GjXHTTdq5xENmRDHabpHw5o+21LkWBY25EaxjwcZa
    Y3qMIOllTZ2iRrXu7fSP6iDjtFCcE2bFAgMBAAGjZzBlMA4GA1UdDwEB/wQEAwIF
    oDATBgNVHSUEDDAKBggrBgEFBQcDAjAdBgNVHQ4EFgQUIY7LzqNTzgyTBE5efHb5
    kZ71BUEwHwYDVR0jBBgwFoAUxZA5kifzo4NniQfGKb+4wruTIFowDQYJKoZIhvcN
    AQELBQADggIBAAK207LaqMrnphF6CFQnkMLbskSpDZsKfqqNB52poRvUrNVUOB1w
    3dSEaBUjhFgUU6yzF+xnuH84XVbjD7qlM3YbdiKvJS9jrm71saCKMNc+b9HSeQAU
    DGY7GPb7Y/LG0GKYawYJcPpvRCNnDLsSVn5N4J1foWAWnxuQ6k57ymWwcddibYHD
    OPakOvO4beAnvax3+K5dqF0bh2Np79YolKdIgUVzf4KSBRN4ZE3AOKlBfiKUvWy6
    nRGvu8O/8VaI0vGaOdXvWA5b61H0o5cm50A88tTm2LHxTXynE3AYriHxsWBbRpoM
    oFnmDaQtGY67S6xGfQbwxrwCFd1l7rGsyBQ17cuusOvMNZEEWraLY/738yWKw3qX
    U7KBxdPWPIPd6iDzVjcZrS8AehUEfNQ5yd26gDgW+rZYJoAFYv0vydMEyoI53xXs
    cpY84qV37ZC8wYicugidg9cFtD+1E0nVgOLXPkHnmc7lIDHFiWQKfOieH+KoVCbb
    zdFu3rhW31ygphRmgszkHwApllCTBBMOqMaBpS8eHCnetOITvyB4Kiu1/nKvVxhY
    exit11KQv8F3kTIUQRm0qw00TSBjuQHKoG83yfimlQ8OazciT+aLpVaY8SOrrNnL
    IJ8dHgTpF9WWHxx04DDzqrT7Xq99F9RzDzM7dSizGxIxonoWcBjiF6n5
    -----END CERTIFICATE-----

  token: eyJhbGciOiJBMTI4R0NNS1ciLCJjdHkiOiJKV1QiLCJlbmMiOiJBMTI4R0NNIiwiaXYiOiJ1MDlBbS0wQXN2S1RMRnFsIiwidGFnIjoiOHJHeVZRVXVFWG15UHlFcm9faWdOQSIsInR5cCI6IkpXVCJ9.fBBmMG7bk_g2zO7L_L9SZg.gqmqBtmLKMFE9Y3B.sULC6VFA_lqpBwHiPLHzcNFz_4hf8B7lfkIF3Uftk42ZnkXLoWcU89dbaHdsTi07pAh7rBV0hBydJEbczZ8BI39vLyK45OU7PJIM1zTvxyVQTe3Od3j92M4Cda33x6XNYc6g4PUKARLXywThi8TNgT9-WBpli_q1mbAlDn2FQDJodl06TY2jbGFdePKnCOtTOWX-Z6UA5QrXRnr-butDEBMt90O_6K3YNXG0s7y0tytxb9mX8TkZyCxYSKUbVUC8ww2bgFyAIQK_d4mSlaf8PBpm2YfMHx-KDutZtHrzrdtOJ63aPUX224SoO2h7pR5MaOMVSuYbgHizZliiQ7e7uM0izpXvEZgrp9P-oT_698Ariw4bF5zB5jZBbuUcRlsKrWJCgdYugLnIvuJd8uOg7exSOYzBjP9OZmXUJAOLWqlg-XcylvVBQLlIA2ec4IKSbmCqt47ZRsal3iyrSE74Su6uSD5T86Kfhtixdg0zt7F1qR92qa_U878sr5sWen-EzFgR9cJ_cR_MPBTlZ86u0ERyVkdomBT59CKWKYlaMNitI6Am_FVSX_a_0L4MWyEjvF6K2p0xUnmJ-59HodURZ8opGPzekXbkAC3zz8_ph-gzq_EPz0jDI93NCh5lKytW4OYSYC2nFvewcgyuoQVUrz0VdDh3yzHVcTdXkl5Hg9QOm872aiUi3k3Bd6FIOWmnH-TJwdV1t8qUPJN4Fiw_Fgjq3ZxHA7ddm6XFhZ4vkxjxFhPTTjudQ5vHyfiLFIQ3NoUUOeGOpc0u3c_NdVyejcmw-ULvcIF2LYeopdPYMtCsT7bxtDXfiLXbXYECtiFW5HmqmIhzZFLAYbQTNutYemg5U6EC1kCP7VjKbCIe-GAgh9HzqtOXifKqTDKo_Th2QlBKGCydauMTW4UEHIdmms1ZG4AKBAVP14_4VmkVIJXCUCNAtMUyH1rMu-DCACuTXnQVgFHF_bd28pdpBU9cWfikJYWvynLb-Ru4OkCeY2V_bY5J-DtTi0jhFxGTpHGrm6jdcQ3m8qoF1dzy1X9Fy_Xa81rdYPofGUmo4NhAtebCcb2uJRd5fGwLmGXsZLguW1tjIyCzVjfnnxHODDZHw5uV1IRoOwrI5bs.S1kGIbgI8l3-q1IDcnR4rA


{{ end }}
