{{ if or (and .Values.mgmtclustercert (eq .Values.mgmtclustercert.enabled true)) (and .Values.standalonecluster (eq .Values.standalonecluster.enabled true))}}

apiVersion: projectcalico.org/v3
kind: LicenseKey
metadata:
  creationTimestamp: null
  name: default
spec:
  certificate: |+
    -----BEGIN CERTIFICATE-----
    MIIFxjCCA66gAwIBAgIQVq3rz5D4nQF1fIgMEh71DzANBgkqhkiG9w0BAQsFADCB
    tTELMAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNh
    biBGcmFuY2lzY28xFDASBgNVBAoTC1RpZ2VyYSwgSW5jMSIwIAYDVQQLDBlTZWN1
    cml0eSA8c2lydEB0aWdlcmEuaW8+MT8wPQYDVQQDEzZUaWdlcmEgRW50aXRsZW1l
    bnRzIEludGVybWVkaWF0ZSBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkwHhcNMTgwNDA1
    MjEzMDI5WhcNMjAxMDA2MjEzMDI5WjCBnjELMAkGA1UEBhMCVVMxEzARBgNVBAgT
    CkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBGcmFuY2lzY28xFDASBgNVBAoTC1Rp
    Z2VyYSwgSW5jMSIwIAYDVQQLDBlTZWN1cml0eSA8c2lydEB0aWdlcmEuaW8+MSgw
    JgYDVQQDEx9UaWdlcmEgRW50aXRsZW1lbnRzIENlcnRpZmljYXRlMIIBojANBgkq
    hkiG9w0BAQEFAAOCAY8AMIIBigKCAYEAwg3LkeHTwMi651af/HEXi1tpM4K0LVqb
    5oUxX5b5jjgi+LHMPzMI6oU+NoGPHNqirhAQqK/k7W7r0oaMe1APWzaCAZpHiMxE
    MlsAXmLVUrKg/g+hgrqeije3JDQutnN9h5oZnsg1IneBArnE/AKIHH8XE79yMG49
    LaKpPGhpF8NoG2yoWFp2ekihSohvqKxa3m6pxoBVdwNxN0AfWxb60p2SF0lOi6B3
    hgK6+ILy08ZqXefiUs+GC1Af4qI1jRhPkjv3qv+H1aQVrq6BqKFXwWIlXCXF57CR
    hvUaTOG3fGtlVyiPE4+wi7QDo0cU/+Gx4mNzvmc6lRjz1c5yKxdYvgwXajSBx2pw
    kTP0iJxI64zv7u3BZEEII6ak9mgUU1CeGZ1KR2Xu80JiWHAYNOiUKCBYHNKDCUYl
    RBErYcAWz2mBpkKyP6hbH16GjXHTTdq5xENmRDHabpHw5o+21LkWBY25EaxjwcZa
    Y3qMIOllTZ2iRrXu7fSP6iDjtFCcE2bFAgMBAAGjZzBlMA4GA1UdDwEB/wQEAwIF
    oDATBgNVHSUEDDAKBggrBgEFBQcDAjAdBgNVHQ4EFgQUIY7LzqNTzgyTBE5efHb5
    kZ71BUEwHwYDVR0jBBgwFoAUxZA5kifzo4NniQfGKb+4wruTIFowDQYJKoZIhvcN
    AQELBQADggIBAAK207LaqMrnphF6CFQnkMLbskSpDZsKfqqNB52poRvUrNVUOB1w
    3dSEaBUjhFgUU6yzF+xnuH84XVbjD7qlM3YbdiKvJS9jrm71saCKMNc+b9HSeQAU
    DGY7GPb7Y/LG0GKYawYJcPpvRCNnDLsSVn5N4J1foWAWnxuQ6k57ymWwcddibYHD
    OPakOvO4beAnvax3+K5dqF0bh2Np79YolKdIgUVzf4KSBRN4ZE3AOKlBfiKUvWy6
    nRGvu8O/8VaI0vGaOdXvWA5b61H0o5cm50A88tTm2LHxTXynE3AYriHxsWBbRpoM
    oFnmDaQtGY67S6xGfQbwxrwCFd1l7rGsyBQ17cuusOvMNZEEWraLY/738yWKw3qX
    U7KBxdPWPIPd6iDzVjcZrS8AehUEfNQ5yd26gDgW+rZYJoAFYv0vydMEyoI53xXs
    cpY84qV37ZC8wYicugidg9cFtD+1E0nVgOLXPkHnmc7lIDHFiWQKfOieH+KoVCbb
    zdFu3rhW31ygphRmgszkHwApllCTBBMOqMaBpS8eHCnetOITvyB4Kiu1/nKvVxhY
    exit11KQv8F3kTIUQRm0qw00TSBjuQHKoG83yfimlQ8OazciT+aLpVaY8SOrrNnL
    IJ8dHgTpF9WWHxx04DDzqrT7Xq99F9RzDzM7dSizGxIxonoWcBjiF6n5
    -----END CERTIFICATE-----

  token: eyJhbGciOiJBMTI4R0NNS1ciLCJjdHkiOiJKV1QiLCJlbmMiOiJBMTI4R0NNIiwiaXYiOiJ5MVRFM0VoSjRIUVo0OUpQIiwidGFnIjoiS0taRzBicU9xTVFwSURGQjB3a0dMZyIsInR5cCI6IkpXVCJ9.MFUn9wx61nxdEMl8WnQOew.BO8asB3cItxUzZ8f.KdLcgpOqOvuabfIK9TI7F7WGqVzLWpUvED0Q_2MPe8YW1nkFUy2Jt059n9uCEqOj5BjaDV4Ncv4nfkxS0CYJJZhEzyvxYsZhgwYt1jN6_r3JfLp568f4FNC_QkJ4QRj4ZfzGbb05Kea7tFFCWZHBIcA9Eryixqqa3dlUiskKHJ7gfl27e83zBHQkKMZPPItLyIVq3Tns1H02FllAFJpHBB1LKnxgE2nkbXaaSeilwYdipvgCLIFCQGcy8qM17X8z4zbOP-MMuqAemdWs3UlUhd2w2tbiRRHgDZJzhj4uiRWaMsAVm5g0ws7qSMP6kpQL2fv0TX-GtH_ZlAPFQ8QZyfznVOFzERFKADFF3oW7alkzvFeK2ISXHX0CVz76SqLq_iE6ZOj5UFoqoMFcnYNe9rGIQYEMrdSS8hGIVgIGOVrWfdlnvU4baYNLtHZilp8L6W0LV6DvT6rMsoCqN2nUpjFlXClZgicoMoPLdTlmj5n0O_TeoxnbbTHYD-TwBtH2eosLMPUVIvIW6hbxTyhP1PhmmNsEpAxVthupjgDg4qJd41Elc2b-lsHFPMiS1LDTZ1Vn8ipVpiYqx1DnQ-AVvzYCFVKCrLC8rA1SzSTW4VjxKXvYRmHtBpxV95iqItrmJiFj6aojzCtu4H0TW4p5-QdWAq2dPfJhkjFt5t32jRXVJTAHiYTZEQeZ6VL1Rmn13QyTAv0iSEfeY3wjP9d_BiVm7GhTYjOX-NeqcIGiUBKP077DwYml5zxhJF5E_QZa4-E4WDZs32mK_pCbhBVz7E1uY0u5P_NEUcqGaHGCSHFMSWskPizn2oY--6iAUZRjy6s1oCX7QzJ7gDEWWs9Uhw-yEXOBTQifdrKKkf_WJuO1osmTbfb6Y6CI9tYmSD9Xw4w492GNSbW-l3j0ftlmrNsJwbxc0AoI1R2KGL72gf1tW1wUttjXzUaCMEzqQ3KFOok6kVV7gHwfgbEmmGXrS1H4js0XZVgCBHvQ_omZmJWGotOUVyhXFjlq3HhBbjTAFu9yztfwR9oFbaTUdwRUgfyPzgB97QtAskLmqNXVsTF6kF4-ekLMKhwrVpzhqpSvraKDY-VOrTv1ApEpVPbblxoBefGAp2EMHDY.n2bi8-KsrcPaEGgxJRE8jw


{{ end }}
