apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: namespace-1
spec: {}
---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: namespace-2
spec: {}
---

apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: namespace-3
spec: {}
