apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: upwork-gnp
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default
  destination:
    name: ce-mgmt
    namespace: default
  source:
    path: charts/upwork-gnp
    repoURL: 'git@github.com:VerodaClient/argocd-charts.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 35
      backoff:
        duration: 30s
        factor: 1
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - allowEmpty=true
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true