apiVersion: v2
appVersion: v3.21.1
dependencies:
- condition: tigera-prometheus-operator.enabled, global.tigera-prometheus-operator.enabled
  name: tigera-prometheus-operator
  repository: ""
  tags:
  - tigera-prometheus-operator
description: Installs the Tigera operator for Calico and Calico Enterprise
home: https://docs.tigera.io/about/about-calico
icon: https://projectcalico.docs.tigera.io/images/felix_icon.png
name: tigera-operator
sources:
- https://github.com/projectcalico/calico/tree/master/charts/tigera-operator
- https://github.com/tigera/operator
version: v3.21.1
