tigera-operator:
  apiServer:
    enabled: true
    apiServerDeployment:
      spec:
        template:
          spec:
            containers:
              - name: calico-apiserver
                resources:
                  requests:
                    memory: 800Mi
                    cpu: 200m
                  limits:
                    memory: 800Mi

  installation:
    kubernetesProvider: "EKS"
    kubeletVolumePluginPath: "None"
#  goldmane:
#    enabled: false

#  whisker:
#    enabled: false

