apiVersion: crd.projectcalico.org/v1
kind: Tier
metadata:
  name: security
spec:
  order: 100
---
apiVersion: crd.projectcalico.org/v1
kind: Tier
metadata:
  name: platform
spec:
  order: 200
---
apiVersion: crd.projectcalico.org/v1
kind: Tier
metadata:
  name: infra
spec:
  order: 300
---

